let DataDetails = [
  {
    id: 1,
    name: "Chocolate Fudge Cake",
    flavor: "Chocolate",
    quantity: 1,
    price: 25.99,
    old_price: 29.99,
    images: "https://imgcdn.floweraura.com/DSC_4152.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 2,
    name: "Vanilla Bean Cake",
    flavor: "Vanilla",
    quantity: 1,
    price: 22.5,
    old_price: 26.99,
    images:
      "https://imgcdn.floweraura.com/vanilla-cake-cak0920171001reg-AA.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 3,
    name: "Strawberry Shortcake",
    flavor: "Strawberry",
    quantity: 1,
    price: 28.75,
    old_price: 32.5,
    images:
      "https://imgcdn.floweraura.com/Strawberry-Cake-Five-Star-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 4,
    name: "Lemon Drizzle Cake",
    flavor: "Lemon",
    quantity: 1,
    price: 21.99,
    old_price: 25.99,
    images: "https://imgcdn.floweraura.com/DSC_7682.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 5,
    name: "Carrot Cake",
    flavor: "Carrot",
    quantity: 1,
    price: 19.99,
    old_price: 23.5,
    images:
      "https://imgcdn.floweraura.com/exquisite-christmas-tree-candle-with-carrot-cake-ven-38-kcct202301-A_0.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 6,
    name: "Red Velvet Cake",
    flavor: "Red Velvet",
    quantity: 1,
    price: 27.5,
    old_price: 31.75,
    images:
      "https://imgcdn.floweraura.com/red-velvety-and-fruity-delight-A-9998510ca-071217.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 7,
    name: "Black Forest Cake",
    flavor: "Chocolate, Cherry",
    quantity: 1,
    price: 31.99,
    old_price: 35.99,
    images: "https://imgcdn.floweraura.com/DSC_6165.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 8,
    name: "Coffee Cake",
    flavor: "Coffee",
    quantity: 1,
    price: 26.5,
    old_price: 30.25,
    images: "https://imgcdn.floweraura.com/DSC_7439.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 9,
    name: "Pineapple Upside Down Cake",
    flavor: "Pineapple",
    quantity: 1,
    price: 29.25,
    old_price: 33.5,
    images:
      "https://imgcdn.floweraura.com/Pineapple-Cake-Five-Star-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 10,
    name: "Coconut Cream Cake",
    flavor: "Coconut",
    quantity: 1,
    price: 24.99,
    old_price: 28.75,
    images:
      "https://imgcdn.floweraura.com/luscious-rasmalai-pista-cream-cake-9815470ca-A.JPG?tr=w-339,h-339,q-70",
  },
  {
    id: 11,
    name: "Blueberry Cheesecake",
    flavor: "Blueberry, Cheese",
    quantity: 1,
    price: 33.75,
    old_price: 37.99,
    images:
      "https://imgcdn.floweraura.com/blueberry-baked-cheesecake-delight-9797150ca-A_0.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 12,
    name: "Raspberry Ripple Cake",
    flavor: "Raspberry",
    quantity: 1,
    price: 27.99,
    old_price: 32.5,
    images:
      "https://imgcdn.floweraura.com/berry-bliss-red-velvet-cake-9797260ca-E_0.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 13,
    name: "Banana Bread Cake",
    flavor: "Banana",
    quantity: 1,
    price: 21.5,
    old_price: 25.99,
    images:
      "https://imgcdn.floweraura.com/chocolate-fudge-cake-usck10001-a.jpg?tr=w-264,q-70",
  },
  {
    id: 14,
    name: "Salted Caramel Cake",
    flavor: "Caramel",
    quantity: 1,
    price: 30.5,
    old_price: 34.99,
    images:
      "https://imgcdn.floweraura.com/chocolate-caramel-cake-9913580ca-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 15,
    name: "Hazelnut Chocolate Cake",
    flavor: "Hazelnut, Chocolate",
    quantity: 1,
    price: 35.99,
    old_price: 39.99,
    images:
      "https://imgcdn.floweraura.com/divine-nutella-hazelnut-cake-9815340ca-A_0.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 16,
    name: "Marble Cake",
    flavor: "Vanilla, Chocolate",
    quantity: 1,
    price: 28.75,
    old_price: 32.5,
    images:
      "https://imgcdn.floweraura.com/brilliant-premium-rainbow-cake-usck0918-a.jpg?tr=w-264,q-70",
  },

  {
    id: 17,
    name: "Tiramisu Cake",
    flavor: "Coffee, Mascarpone",
    quantity: 1,
    price: 32.99,
    old_price: 36.99,
    images:
      "https://imgcdn.floweraura.com/yummy-tiramisu-cake-9913520ca-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 18,
    name: "Peanut Butter Chocolate Cake",
    flavor: "Peanut Butter, Chocolate",
    quantity: 1,
    price: 34.5,
    old_price: 38.75,
    images: "https://imgcdn.floweraura.com/DSC_8414.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 19,
    name: "Almond Joy Cake",
    flavor: "Almond, Coconut, Chocolate",
    quantity: 1,
    price: 29.99,
    old_price: 33.5,
    images:
      "https://imgcdn.floweraura.com/almond-rocher-cake-9913560ca-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 20,
    name: "Mango Passionfruit Cake",
    flavor: "Mango, Passionfruit",
    quantity: 1,
    price: 31.25,
    old_price: 35.5,
    images:
      "https://imgcdn.floweraura.com/nutty-mango-cake-9963010ca-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 21,
    name: "Key Lime Pie Cake",
    flavor: "Key Lime",
    quantity: 1,
    price: 27.75,
    old_price: 31.99,
    images:
      "https://imgcdn.floweraura.com/berry-bliss-red-velvet-cake-9797260ca-E_0.jpg?tr=w-304,q-70",
  },
  {
    id: 22,
    name: "Cookies and Cream Cake",
    flavor: "Cookies, Cream",
    quantity: 1,
    price: 33.5,
    old_price: 37.99,
    images:
      "https://imgcdn.floweraura.com/heartilicious-pineapple-9988810cb-A_0.jpg?tr=w-339,h-339,q-70",
  },

  {
    id: 23,
    name: "Cherry Almond Cake",
    flavor: "Cherry, Almond",
    quantity: 1,
    price: 28.99,
    old_price: 32.99,
    images:
      "https://imgcdn.floweraura.com/Cherry+Topped+Black+Forest+Cake+A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 24,
    name: "Mint Chocolate Chip Cake",
    flavor: "Mint, Chocolate",
    quantity: 1,
    price: 30.99,
    old_price: 34.75,
    images:
      "https://imgcdn.floweraura.com/spooky-stare-chocolate-cake-9799470ca-AA.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 25,
    name: "Caramel Apple Cake",
    flavor: "Caramel, Apple",
    quantity: 1,
    price: 26.75,
    old_price: 30.25,
    images:
      "https://imgcdn.floweraura.com/chocolate-caramel-cake-9913580ca-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 26,
    name: "Lavender Honey Cake",
    flavor: "Lavender, Honey",
    quantity: 1,
    price: 35.25,
    old_price: 39.5,
    images:
      "https://imgcdn.floweraura.com/simply-sinful-butterscotch-cake-9871050ca-AAA.jpg?tr=w-264,q-70",
  },
  {
    id: 27,
    name: "Raspberry Chocolate Truffle Cake",
    flavor: "Raspberry, Chocolate",
    quantity: 1,
    price: 36.99,
    old_price: 40.99,
    images:
      "https://imgcdn.floweraura.com/blue-orchids-bouquet-n-choco-cake-9813430co-C_1.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 28,
    name: "Lemon Blueberry Cake",
    flavor: "Lemon, Blueberry",
    quantity: 1,
    price: 29.5,
    old_price: 33.75,
    images:
      "https://imgcdn.floweraura.com/eggless-blueberry-cake-9913250ca_0.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 29,
    name: "Red Wine Chocolate Cake",
    flavor: "Red Wine, Chocolate",
    quantity: 1,
    price: 38.25,
    old_price: 42.5,
    images:
      "https://imgcdn.floweraura.com/hearty-dainty-red-velvet-cake-9827290ca+A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 30,
    name: "S'mores Cake",
    flavor: "Chocolate, Marshmallow, Graham Cracker",
    quantity: 1,
    price: 32.99,
    old_price: 36.99,
    images: "https://imgcdn.floweraura.com/DSC_3290.jpg?tr=w-264,q-70",
  },
  {
    id: 31,
    name: "Matcha Green Tea Cake",
    flavor: "Matcha Green Tea",
    quantity: 1,
    price: 34.75,
    old_price: 38.99,
    images:
      "https://imgcdn.floweraura.com/sumptuous-green-cake-9852930ca-B.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 32,
    name: "Orange Creamsicle Cake",
    flavor: "Orange, Cream",
    quantity: 1,
    price: 31.25,
    old_price: 35.5,
    images:
      "https://imgcdn.floweraura.com/Fruit-Cake-Eggless-cak145-A.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 33,
    name: "Pistachio Rose Cake",
    flavor: "Pistachio, Rose",
    quantity: 1,
    price: 37.5,
    old_price: 41.99,
    images:
      "https://imgcdn.floweraura.com/mango-compote-pistachio-cake-9801030ca-A_0.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 34,
    name: "Chai Spice Cake",
    flavor: "Chai Spice",
    quantity: 1,
    price: 30.99,
    old_price: 34.99,
    images: "https://imgcdn.floweraura.com/PMU02-D.jpg?tr=w-264,q-70",
  },
  {
    id: 35,
    name: "Coconut Lime Cake",
    flavor: "Coconut, Lime",
    quantity: 1,
    price: 33.25,
    old_price: 37.5,
    images:
      "https://imgcdn.floweraura.com/floral-white-forest-cake-9794050ca-A_0.jpg?tr=w-264,q-70",
  },
  {
    id: 36,
    name: "Cinnamon Roll Cake",
    flavor: "Cinnamon",
    quantity: 1,
    price: 28.75,
    old_price: 32.99,
    images:
      "https://imgcdn.floweraura.com/rock-n-roll-new-year-cake-9830840ca-AAA.jpg?tr=w-339,h-339,q-70",
  },
  {
    id: 37,
    name: "Mocha Espresso Cake",
    flavor: "Mocha, Espresso",
    quantity: 1,
    price: 35.99,
    old_price: 39.99,
    images:
      "https://imgcdn.floweraura.com/buttercream-chocolate-swirl-cake-9871040ca-A_0.jpg?tr=w-264,q-70",
  },
  {
    id: 38,
    name: "Pumpkin Spice Cake",
    flavor: "Pumpkin Spice",
    quantity: 1,
    price: 30.5,
    old_price: 34.75,
    images:
      "https://imgcdn.floweraura.com/irresistible-belgian-chocolate-cake-9815330ca-A_0.jpg?tr=w-264,q-70",
  },
  {
    id: 39,
    name: "Gingerbread Cake",
    flavor: "Gingerbread",
    quantity: 1,
    price: 32.25,
    old_price: 36.5,
    images:
      "https://imgcdn.floweraura.com/rainbow-vanilla-cream-cake-9788760ca-A_0.jpg?tr=w-264,q-70",
  },
  {
    id: 40,
    name: "Cherry Chocolate Chip Cake",
    flavor: "Cherry, Chocolate Chip",
    quantity: 1,
    price: 34.99,
    old_price: 39.25,
    images: "https://imgcdn.floweraura.com/DSC_6089.jpg?tr=w-339,h-339,q-70",
  },
];
export default DataDetails;
