let ProductDetail = [
  {
    id: 1,
    image:
      "https://www.pintola.in/cdn/shop/products/1_18b3b3cb-2d29-4f81-981c-2042968522b6_600x.jpg?v=1670671117",
    title: "All Natural Peanut Butter",
    rs: 163,
    ors: 175,
    brand: "Creamy / 350gm",
    dis: 8,
    des: "Made with just one ingredient, our All Natural Peanut Butter is as natural as it can get. The best addition to your diet to increase the protein intake.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time. Ideal for Weight watcher, Athletes and for overall health.",
    lie: " 9 Months",
  },
  {
    id: 2,
    image:
      "https://www.pintola.in/cdn/shop/products/1_12c8008c-9c77-4e8b-8f9a-c45115b4f687_600x.jpg?v=1670670579",
    title: "All Natural  Peanut Butter",
    rs: 185,
    ors: 199,
    brand: "Crunchy / 350gm",
    dis: 7,
    des: "Made with just one ingredient, organic peanuts certified with USDA Organic, SGS Organic, India Organic and Jaivik Bharat. Our All Natural Organic Peanut Butter is as natural and organic as it can get.The best addition to your diet to increase the protein intake.All PINTOLA® Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India’s favorite Nut Butters daily so that you get the Freshest Product every time.Ideal for Weight watcher, Athletes and for over all health.",
    lie: " 9 Months",
  },
  {
    id: 3,
    image:
      "https://www.pintola.in/cdn/shop/products/1_3a4749c4-8b9e-4a8f-b62a-5f514a7d703c_600x.jpg?v=1670829499",
    title: "Classic Peanut Butter",
    rs: 149,
    ors: 160,
    brand: "Crunchy / 350gm",
    dis: 8,
    des: "Made with Original American Recipe. Our Classic Peanut Butter is Ideal for you. It helps in weight management by keeping you satisfied for a longer period of time.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym & Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 18 Months",
  },
  {
    id: 4,
    image:
      "https://www.pintola.in/cdn/shop/products/1_c593df28-8e17-4372-bf9f-be10f16f9de9_600x.jpg?v=1670672381",
    title: "Dark Chocolate Peanut Butter",
    rs: 185,
    ors: 199,
    brand: "Crunchy / 350gm",
    dis: 6,
    des: "Pintola Dark Chocolate Peanut Butter is the best chocolate flavored peanut butter in India! It is irresistibly delicious and has an utterly smooth texture. No artificial colorings or harmful preservatives are used in this product.All PINTOLA® Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory.We manufacture India’s favorite Nut Butters daily so that you get the fresh product every time you buy one.",
    lie: " 12 Months",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Months",
  },
  {
    id: 1,
    image:
      "https://www.pintola.in/cdn/shop/products/1_18b3b3cb-2d29-4f81-981c-2042968522b6_600x.jpg?v=1670671117",
    title: "All Natural Peanut Butter",
    rs: 163,
    ors: 175,
    brand: "Creamy / 350gm",
    dis: 8,
    des: "Made with just one ingredient, our All Natural Peanut Butter is as natural as it can get. The best addition to your diet to increase the protein intake.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time. Ideal for Weight watcher, Athletes and for overall health.",
    lie: " 9 Months",
  },
  {
    id: 2,
    image:
      "https://www.pintola.in/cdn/shop/products/1_12c8008c-9c77-4e8b-8f9a-c45115b4f687_600x.jpg?v=1670670579",
    title: "All Natural  Peanut Butter",
    rs: 185,
    ors: 199,
    brand: "Crunchy / 350gm",
    dis: 7,
    des: "Made with just one ingredient, organic peanuts certified with USDA Organic, SGS Organic, India Organic and Jaivik Bharat. Our All Natural Organic Peanut Butter is as natural and organic as it can get.The best addition to your diet to increase the protein intake.All PINTOLA® Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India’s favorite Nut Butters daily so that you get the Freshest Product every time.Ideal for Weight watcher, Athletes and for over all health.",
    lie: " 9 Months",
  },
  {
    id: 3,
    image:
      "https://www.pintola.in/cdn/shop/products/1_3a4749c4-8b9e-4a8f-b62a-5f514a7d703c_600x.jpg?v=1670829499",
    title: "Classic Peanut Butter",
    rs: 149,
    ors: 160,
    brand: "Crunchy / 350gm",
    dis: 8,
    des: "Made with Original American Recipe. Our Classic Peanut Butter is Ideal for you. It helps in weight management by keeping you satisfied for a longer period of time.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym & Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 18 Months",
  },
  {
    id: 4,
    image:
      "https://www.pintola.in/cdn/shop/products/1_c593df28-8e17-4372-bf9f-be10f16f9de9_600x.jpg?v=1670672381",
    title: "Dark Chocolate Peanut Butter",
    rs: 185,
    ors: 199,
    brand: "Crunchy / 350gm",
    dis: 6,
    des: "Pintola Dark Chocolate Peanut Butter is the best chocolate flavored peanut butter in India! It is irresistibly delicious and has an utterly smooth texture. No artificial colorings or harmful preservatives are used in this product.All PINTOLA® Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory.We manufacture India’s favorite Nut Butters daily so that you get the fresh product every time you buy one.",
    lie: " 12 Months",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Months",
  },
  {
    id: 1,
    image:
      "https://www.pintola.in/cdn/shop/products/1_18b3b3cb-2d29-4f81-981c-2042968522b6_600x.jpg?v=1670671117",
    title: "All Natural Peanut Butter",
    rs: 163,
    ors: 175,
    brand: "Creamy / 350gm",
    dis: 8,
    des: "Made with just one ingredient, our All Natural Peanut Butter is as natural as it can get. The best addition to your diet to increase the protein intake.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time. Ideal for Weight watcher, Athletes and for overall health.",
    lie: " 9 Months",
  },
  {
    id: 2,
    image:
      "https://www.pintola.in/cdn/shop/products/1_12c8008c-9c77-4e8b-8f9a-c45115b4f687_600x.jpg?v=1670670579",
    title: "All Natural  Peanut Butter",
    rs: 185,
    ors: 199,
    brand: "Crunchy / 350gm",
    dis: 7,
    des: "Made with just one ingredient, organic peanuts certified with USDA Organic, SGS Organic, India Organic and Jaivik Bharat. Our All Natural Organic Peanut Butter is as natural and organic as it can get.The best addition to your diet to increase the protein intake.All PINTOLA® Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India’s favorite Nut Butters daily so that you get the Freshest Product every time.Ideal for Weight watcher, Athletes and for over all health.",
    lie: " 9 Months",
  },
  {
    id: 3,
    image:
      "https://www.pintola.in/cdn/shop/products/1_3a4749c4-8b9e-4a8f-b62a-5f514a7d703c_600x.jpg?v=1670829499",
    title: "Classic Peanut Butter",
    rs: 149,
    ors: 160,
    brand: "Crunchy / 350gm",
    dis: 8,
    des: "Made with Original American Recipe. Our Classic Peanut Butter is Ideal for you. It helps in weight management by keeping you satisfied for a longer period of time.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym & Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 18 Months",
  },
  {
    id: 4,
    image:
      "https://www.pintola.in/cdn/shop/products/1_c593df28-8e17-4372-bf9f-be10f16f9de9_600x.jpg?v=1670672381",
    title: "Dark Chocolate Peanut Butter",
    rs: 185,
    ors: 199,
    brand: "Crunchy / 350gm",
    dis: 6,
    des: "Pintola Dark Chocolate Peanut Butter is the best chocolate flavored peanut butter in India! It is irresistibly delicious and has an utterly smooth texture. No artificial colorings or harmful preservatives are used in this product.All PINTOLA® Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory.We manufacture India’s favorite Nut Butters daily so that you get the fresh product every time you buy one.",
    lie: " 12 Months",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/products/1_26dc3f1c-a999-4b6d-908a-d0314d7287b3_600x.jpg?v=1670829969",
    title: "All  Honey Peanut Butte",
    rs: 185,
    ors: 199,
    brand: "Creamy / 350gm",
    dis: 7,
    des: "The perfect combination of delicious honey and the finest of peanuts. All Natural Honey Peanut Butter is one of the most popular products amongst our customers. They simply can't get enough of this perfect creation!! The goodness of honey added to the All Natural peanut paste makes this product the best addition to a diet, one can ever ask for. High in protein and fibre, and ZERO in trans fat.All PINTOLA Products are made up of the finest grade, fresh and nutritious ingredients from an ISO 22000 Certified and FSSAI approved Factory. We manufacture India's favorite Nut Butters daily so that you get the Freshest Product every time you buy one.Suitable for all age groups. Ideal for Gym, Fitness Enthusiasts, Athletes & all Foodies!",
    lie: " 9 Month",
  },
];
export { ProductDetail };
