let RecipesData = [
  {
    id: 1,
    image:
      "https://www.pintola.in/cdn/shop/articles/Pintola_noodles_1_a60e6b39-4e08-43b3-a526-f89df28100b5_1000x.jpg?v=1682574587",
    title: "Pintola Peanut Butter Chilli Noodles",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "1 pack of noodles",
    ing2: "1/2 cup Pintola Peanut Butter",
    ing3: "2 tbsp soysauce,1 tbsp vinegar",
    ing4: "1 tbsp chilli sauce",
    ing5: "1 tbsp sesame oil",
    ing6: "1 tbsp minced ginger",
    ing7: "1 cup sliced veggies (bell peppers, carrots,cabbage, etc.)",
    ing8: "Salt, to taste",
    ing9: "Water, as required",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review: "",
  },

  {
    id: 2,
    image:
      "https://www.pintola.in/cdn/shop/articles/with_product_2_600x.jpg?v=1682573527",
    title: "Pintola Peanut Butter & Jelly Bread Pudding",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "For the eggless custard:",
    ing2: "500ml milk",
    ing3: "3 tbsp custard powder (or cornflour)",
    ing4: "1 tbsp vanilla extract if you’re not using custard powder",
    ing5: "3 tbsp brown sugar",
    ing6: "8 thick slices of brioche",
    ing7: " 4 tbsp Pintola Crunchy peanut butter",
    ing8: "4 tbsp strawberry jam (or jelly of choice)",
    ing9: " 2 tbsp Pintola creamy peanut butter",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review:
      "Pintola Peanut butter & jelly is a combination that never gets old! Here’s my traybake version that turns this classic into a luscious bread pudding.",
  },
  {
    id: 3,
    image:
      "https://www.pintola.in/cdn/shop/articles/Pintola_granola_ae91f103-ef8a-4ab5-8c59-62347d251389_600x.jpg?v=1682574657",
    title: "Pintola Peanut Butter Granola Recipe",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "2 1/2 cups rolled oats",
    ing2: "1/4 cup unsweetened peanut butter",
    ing3: "1/2 cup maple syrup",
    ing4: "1/8th cup coconut oil",
    ing5: "1 tsp cinnamon",
    ing6: "Pinch of salt",
    ing7: "1/2 cup dark chocolate chips",
    ing8: "Pinch of salt",
    ing9: "1/2 cup dark chocolate chips",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review: "A simple healthy nutritious and quick granola recipe.",
  },
  {
    id: 4,
    image:
      "https://www.pintola.in/cdn/shop/articles/Cashew_Butter_600x.png?v=1620284930",
    title: "Pintola Cashew Butter Oat Meal",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "1 cup oats",
    ing2: "2 cups water or milk",
    ing3: "1 tbsp of Pintola All Natural Cashew Butter (16 g)",
    ing4: "Chopped fruits of your choices",
    ing5: "Chopped fruits of your choices",
    ing6: "Chopped fruits of your choices",
    ing7: "Chopped fruits of your choices",
    ing8: "Chopped fruits of your choices",
    ing9: "Chopped fruits of your choices",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review: "",
  },
  {
    id: 5,
    image:
      "https://www.pintola.in/cdn/shop/articles/Salad_With_Almond_Butter_600x.jpg?v=1620284955",
    title: "Pintola Almond Butter Salad",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "Choice of cut vegetables and fruits",
    ing2: "2 tbsp Pintola All Natural Almond Butter (32 g)",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins5: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins6: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins7: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins8: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins9: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",

    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review: "",
  },
  {
    id: 6,
    image:
      "https://www.pintola.in/cdn/shop/articles/Classic_600x.png?v=1620285014",
    title: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "2 tbsp Pintola Classic Peanut Butter (32 g)",
    ing2: "2 tbsp mix fruit jam",
    ing3: "2 slices of multigrain bread",
    ing4: "2 slices of multigrain bread",
    ing5: "2 slices of multigrain bread",
    ing6: "2 slices of multigrain bread",
    ing7: "2 slices of multigrain bread",
    ing8: "2 slices of multigrain bread",
    ing9: "2 slices of multigrain bread",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review: "",
  },
  {
    id: 7,
    image:
      "https://www.pintola.in/cdn/shop/articles/Organic_600x.png?v=1620285059",
    title: "Pintola Smoothie",
    small: "1 min read",
    other1: "Pintola Peanut Butter Chilli Noodles ",
    other2: "Pintola Peanut Butter & Jelly Bread Pudding",
    other3: "Pintola Peanut Butter Granola Recipe",
    other4: "Pintola Cashew Butter Oat Meal",
    other5: "Pintola Almond Butter Salad",
    other6: "Pintola Peanut Butter & Jam Multigrain Sandwich",
    other7: "Pintola Smoothie",

    ing1: "1 cup of milk (250 ml)",
    ing2: "2 tbsp Pintola All Natural Organic Peanut Butter (32 g)  ",
    ing3: "1/2 tbsp natural honey",
    ing4: "1/2 tbsp natural honey",
    ing5: "1/2 tbsp natural honey",
    ing6: "1/2 tbsp natural honey",
    ing7: "1/2 tbsp natural honey",
    ing8: "1/2 tbsp natural honey",
    ing9: "1/2 tbsp natural honey",

    ins1: "Cook the noodles according to the instructions on the packet, and keep them aside.",
    ins2: "In a bowl, mix Pintola Peanut Butter, soy sauce, vinegar, chilli sauce, and salt. Mix well until smooth.",
    ins3: "Heat sesame oil in a pan, and add minced garlic and ginger. Saute for 30 seconds.",
    ins4: "Add sliced vegetables to the pan, and saute for 3-4 minutes.",
    ins5: "Add the peanut butter mixture to the pan, and cook for 1-2 minutes.",
    ins6: "Add the cooked noodles to the pan, and toss well until the noodles are coated with the sauce.",
    ins7: "Add water as required to adjust the consistency of the sauce.",
    ins8: "Cook for another 2-3 minutes until the noodles are heated through.",
    ins9: "Serve hot and enjoy your delicious Pintola Peanut Chilli Noodles!",
    review: "",
  },
];

export { RecipesData };
